# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFlipkartuser2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_flipkartuser2(self):
    self.driver.get("https://www.flipkart.com/")
    self.driver.set_window_size(1514, 974)
    self.driver.find_element(By.LINK_TEXT, "Mobiles").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2WDRax").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2WDRax").click()
    self.driver.find_element(By.LINK_TEXT, "Mobile Accessories").click()
    self.driver.find_element(By.LINK_TEXT, "Headphones & Headsets").click()
    self.driver.find_element(By.CSS_SELECTOR, ".QvtND5 > span").click()
    self.driver.execute_script("window.scrollTo(0,551)")
    self.driver.execute_script("window.scrollTo(0,613.5)")
    self.driver.execute_script("window.scrollTo(0,657)")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2x6kFl").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3IxutE").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3IxutE").send_keys("boa")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_38vbm7 .\\_24_Dny").click()
    self.driver.find_element(By.CSS_SELECTOR, ".THxusM > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,562)")
    self.driver.execute_script("window.scrollTo(0,1493)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(5) div:nth-child(4) .\\_2rpwqI > div:nth-child(1) > div").click()
    self.vars["win321"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win321"])
    element = self.driver.find_element(By.CSS_SELECTOR, ".IMZJg1 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3v1-ww").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_3v1-ww > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
