# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFlipkartuser1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_flipkartuser1(self):
    self.driver.get("https://www.flipkart.com/")
    self.driver.set_window_size(1514, 974)
    self.driver.find_element(By.LINK_TEXT, "Powerbank").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1mIbUg:nth-child(2) .kJjFO0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1mIbUg:nth-child(2) .kJjFO0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Audio").click()
    self.driver.find_element(By.LINK_TEXT, "Headphones & Headsets").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2VGJMH .kJjFO0").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".QvtND5").click()
    self.driver.execute_script("window.scrollTo(0,453.5)")
    self.driver.execute_script("window.scrollTo(0,593.5)")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3IxutE").send_keys("boat")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_38vbm7:nth-child(2) .\\_24_Dny").click()
    self.driver.find_element(By.CSS_SELECTOR, ".THxusM > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) div:nth-child(2) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) div:nth-child(3) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) div:nth-child(3) .\\_396cs4").click()
    self.vars["win9729"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9729"])
    self.driver.switch_to.window(self.vars["root"])
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.window(self.vars["win9729"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) div:nth-child(2) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(5) div:nth-child(2) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,1196)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(5) div:nth-child(4) .CXW8mj").click()
    self.vars["win5901"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win5901"])
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_3v1-ww")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".P9aMAP > .q6DClP").click()
    self.driver.execute_script("window.scrollTo(0,3808)")
    self.driver.find_element(By.LINK_TEXT, "All questions").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".\\_396cs4").click()
    self.vars["win4275"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4275"])
    self.driver.switch_to.window(self.vars["win5901"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win4275"])
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3v1-ww").click()
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["undefined"])
  
