# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSnapdealuser2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_snapdealuser2(self):
    self.driver.get("https://www.snapdeal.com/")
    self.driver.set_window_size(1514, 974)
    self.driver.find_element(By.CSS_SELECTOR, "#category3Data p:nth-child(12) .headingText").click()
    self.driver.execute_script("window.scrollTo(0,725)")
    self.driver.execute_script("window.scrollTo(0,3923)")
    self.driver.execute_script("window.scrollTo(0,332)")
    self.driver.find_element(By.CSS_SELECTOR, ".js-view-more").click()
    self.driver.execute_script("window.scrollTo(0,453)")
    self.driver.find_element(By.CSS_SELECTOR, ".sschild:nth-child(5) > .filters-list:nth-child(13) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".applyFilters").click()
    self.driver.execute_script("window.scrollTo(0,6115.5)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#\\36 77789732148 .hashAdded .wooble").click()
    self.vars["win6827"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win6827"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".product-relative:nth-child(6) .wooble").click()
    self.vars["win7285"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win7285"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win6827"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, "#category3Data p:nth-child(12) .headingText").click()
    self.driver.switch_to.window(self.vars["win6827"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".js-view-more").click()
    self.driver.execute_script("window.scrollTo(0,243)")
    self.driver.find_element(By.CSS_SELECTOR, ".sschild:nth-child(5) > .filters-list:nth-child(13) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".applyFilters").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#\\36 77789732148 .wooble").click()
    self.vars["win463"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win463"])
  
